### ISSUE TITLE
python.hpp conflict: parameter master vs python_parameter master

### ISSUE THREAD

**Issue by mloskot** [boostorg/parameter#19]
TBH, I am not clear where this bug report belongs to: boostorg/boost, boostorg/parameter or boostorg/parameter_python. Trying here.

On Linux, I've got fresh super-project at `master`, bootstrapped, while deploying the headers I'm getting

```
$ b2 headers
Performing configuration checks

    - default address-model    : 64-bit
    - default architecture     : x86
    - symlinks supported       : yes
error: Cannot create link boost/parameter/python.hpp to libs/parameter/include/boost/parameter/python.hpp.
error: Link previously defined to another file, libs/parameter_python/include/boost/parameter/python.hpp.```
```

That is because the Boost super-project points to the two master which both include the `python.hpp`.

`https://github.com/boostorg/parameter_python/tree/master/include/boost/parameter/python.hpp`
conflicts with
`https://github.com/boostorg/parameter/blob/master/include/boost/parameter/python.hpp`

**Comment by eldiener** [comment]
I was going to fix this but Peter has already done so. Please pull parameter again and retry b2 headers.

**Comment by mloskot** [comment]
@eldiener Yeah, I've managed to work around it. Thanks
