### ISSUE TITLE
Tests for msvc failures are not failing

### ISSUE THREAD

**Issue by eldiener** [boostorg/parameter#32]
The tests for parameter_msvc_fail_tests are not failing for msvc-8.0, msvc-9.0, msvc-10.0, and msvc-11.0. These tests are the compile-fail evaluate_category.cpp test and the compile-fail preprocessor_eval_category.cpp test. I am less concerned than usual about these test failures since these are fairly old version of the vc++ compiler, and just may indicate deficiencies in those compilers. But still these test failures should be looked at.

**Comment by CromwellEnage** [comment]
I've changed evaluate_category.cpp and preprocessor_eval_category.cpp so that the tests pass for those compilers.
