### ISSUE TITLE
Merging 'develop' changes to 'master'

### ISSUE THREAD

**Issue by eldiener** [boostorg/parameter#72]
I would like to move forward with merging the 'develop' changes which Cromwell Enage has been making to improve the Parameter library to the 'master' branch, so that those changes can be part of the next release of Boost.

With what other Boost libraries do we need to sync in order to merge Parameter 'develop' to 'master' ? As I understand it we probably need to sync this merge with Accumulators, Log, and Convert. Are there other libraries with which we need to sync the changes as we go to the 'master' branch ?

**Comment by CromwellEnage** [comment]
I have release notes for this library set up in HTML format.  How shall I submit them?

**Comment by CromwellEnage** [comment]
With Boost 1.70 closed for major changes today, it looks like we'll have to wait until after release, then target Boost 1.71 instead.

**Comment by pdimov** [comment]
FWIW, I noticed that @jzmaddock intends to merge Graph to master based on https://github.com/boostorg/graph/pull/164, which by the look of the CI results seems to be blocked on Parameter being merged first.

**Comment by jzmaddock** [comment]
Yep, can't merge anything from Graph really till this is merged.

**Comment by CromwellEnage** [comment]
Good sirs,

I've created PR #77 on boostorg/parameter for your review.  If you approve,
I will merge it.

Very respectfully,
Cromwell D. Enage

**Comment by CromwellEnage** [comment]
Okay, I've merged the PR since all checks passed, so Graph should be good to go.

**Comment by jzmaddock** [comment]
Many thanks for that - it's much appreciated!

**Comment by CromwellEnage** [comment]
I've created pull requests boostorg/accumulators#30, boostorg/lockfree#50, and boostorg/signals2#35 to help complete the syncing process for the master branch.

**Comment by jzmaddock** [comment]
Ping?????

Can we merge to master yet?

**Comment by CromwellEnage** [comment]
Sorry, merging the new documentation now.

**Comment by Lastique** [comment]
Develop was merged a while ago.
